//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SST_LibControladores.Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GT_TiposListas {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GT_TiposListas() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SST_LibControladores.Recursos.GT_TiposListas", typeof(GT_TiposListas).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 10.
        /// </summary>
        internal static string EntidadesFinancierasGMF {
            get {
                return ResourceManager.GetString("EntidadesFinancierasGMF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 9.
        /// </summary>
        internal static string EstadoCuenta {
            get {
                return ResourceManager.GetString("EstadoCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 2.
        /// </summary>
        internal static string EstadosSistema {
            get {
                return ResourceManager.GetString("EstadosSistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1.
        /// </summary>
        internal static string LlavesCifrado {
            get {
                return ResourceManager.GetString("LlavesCifrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 5.
        /// </summary>
        internal static string MotivoConsulta {
            get {
                return ResourceManager.GetString("MotivoConsulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 3.
        /// </summary>
        internal static string Notificaciones {
            get {
                return ResourceManager.GetString("Notificaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 7.
        /// </summary>
        internal static string Oficinas {
            get {
                return ResourceManager.GetString("Oficinas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 6.
        /// </summary>
        internal static string TipoIdentificacion {
            get {
                return ResourceManager.GetString("TipoIdentificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 4.
        /// </summary>
        internal static string TipoInformacionConsulta {
            get {
                return ResourceManager.GetString("TipoInformacionConsulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 8.
        /// </summary>
        internal static string TiposCuentas {
            get {
                return ResourceManager.GetString("TiposCuentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 11.
        /// </summary>
        internal static string TiposRegion {
            get {
                return ResourceManager.GetString("TiposRegion", resourceCulture);
            }
        }
    }
}
