//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SST_LibModelos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_SSTEntities : DbContext
    {
        public db_SSTEntities()
            : base("name=db_SSTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbl_Estados> tbl_Estados { get; set; }
        public DbSet<tbl_Modulos> tbl_Modulos { get; set; }
        public DbSet<tbl_Perfiles> tbl_Perfiles { get; set; }
        public DbSet<tbl_PerfilesUsuarios> tbl_PerfilesUsuarios { get; set; }
        public DbSet<tbl_Permisos> tbl_Permisos { get; set; }
        public DbSet<tbl_TiposDocumentos> tbl_TiposDocumentos { get; set; }
        public DbSet<tbl_Usuarios> tbl_Usuarios { get; set; }
    }
}
