//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SST_LibModelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Permisos
    {
        public int IdPermiso { get; set; }
        public int IdPerfil { get; set; }
        public int IdModulo { get; set; }
    
        public virtual tbl_Modulos tbl_Modulos { get; set; }
        public virtual tbl_Perfiles tbl_Perfiles { get; set; }
    }
}
