//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SST_LibModelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PerfilesUsuarios
    {
        public int IdPerfilUsuario { get; set; }
        public int IdPerfil { get; set; }
        public int IdUsuario { get; set; }
    
        public virtual tbl_Perfiles tbl_Perfiles { get; set; }
        public virtual tbl_Usuarios tbl_Usuarios { get; set; }
    }
}
