//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SST_LibModelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Perfiles
    {
        public tbl_Perfiles()
        {
            this.tbl_Permisos = new HashSet<tbl_Permisos>();
        }
    
        public int IdPerfil { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public int IdEstado { get; set; }
    
        public virtual tbl_Estados tbl_Estados { get; set; }
        public virtual tbl_PerfilesUsuarios tbl_PerfilesUsuarios { get; set; }
        public virtual ICollection<tbl_Permisos> tbl_Permisos { get; set; }
    }
}
