//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SST_LibModelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Usuarios
    {
        public int IdUsuario { get; set; }
        public string Documento { get; set; }
        public int IdTipoDocumento { get; set; }
        public string Nombre { get; set; }
        public string Usuario { get; set; }
        public string Clave { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public int IdEstado { get; set; }
    
        public virtual tbl_Estados tbl_Estados { get; set; }
        public virtual tbl_PerfilesUsuarios tbl_PerfilesUsuarios { get; set; }
        public virtual tbl_TiposDocumentos tbl_TiposDocumentos { get; set; }
    }
}
