//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SST_LibModelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Modulos
    {
        public tbl_Modulos()
        {
            this.tbl_Permisos = new HashSet<tbl_Permisos>();
        }
    
        public int IdModulo { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public int IdEstado { get; set; }
    
        public virtual tbl_Estados tbl_Estados { get; set; }
        public virtual ICollection<tbl_Permisos> tbl_Permisos { get; set; }
    }
}
