//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SST_LibModelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Estados
    {
        public tbl_Estados()
        {
            this.tbl_Modulos = new HashSet<tbl_Modulos>();
            this.tbl_Perfiles = new HashSet<tbl_Perfiles>();
            this.tbl_Usuarios = new HashSet<tbl_Usuarios>();
        }
    
        public int IdEstado { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<tbl_Modulos> tbl_Modulos { get; set; }
        public virtual ICollection<tbl_Perfiles> tbl_Perfiles { get; set; }
        public virtual ICollection<tbl_Usuarios> tbl_Usuarios { get; set; }
    }
}
