//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SST_LibModelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Permisos
    {
        public int IdPermiso { get; set; }
        public int IdPerfil { get; set; }
        public int IdModulo { get; set; }
    
        public virtual tbl_Modulos tbl_Modulos { get; set; }
        public virtual tbl_Perfiles tbl_Perfiles { get; set; }
    }
}
